module Absbrick where

-- Haskell module generated by the BNF converter


newtype CIdent = CIdent String deriving (Eq,Ord,Show)
data Program =
   Progr [FunDeclaration]
  deriving (Eq,Ord,Show)

data Stm =
   SIf Exp [Stm]
 | SIfElse Exp [Stm] [Stm]
 | SJump JumpStm
 | SExp Exp
 | SFunDef FunDeclaration
  deriving (Eq,Ord,Show)

data JumpStm =
   SjumpReturn
 | SjumpReturnV Exp
 | SjumpBreak
 | SjumpBreakV Exp
 | SjumpContinue
 | SjumpContinueV Exp
  deriving (Eq,Ord,Show)

data Exp =
   ENone
 | EFunNone [Stm]
 | EAsign CIdent Exp
 | EYield Exp
 | ETrue
 | EFalse
 | EFor CIdent Exp Exp [Stm]
 | EWhile Exp [Stm]
 | EInt Integer
 | ENegInt Integer
 | EString String
 | EIdent CIdent
 | EFunPar Exp [Exp]
  deriving (Eq,Ord,Show)

data FunParam =
   FunParam CIdent
  deriving (Eq,Ord,Show)

data FunDeclaration =
   FunDec CIdent [FunParam] [Stm]
  deriving (Eq,Ord,Show)

